export default {name:'business',content:[
    {e:'income test',c:'收入检查'},
    {e:'asset test',c:'资产检查'},
    {e:'capital gains tax',c:'资本增值税'},
    {e:'premium',c:'保费'},
    {e:'goods and service tax',c:'消费税'},
    {e:'turnover',c:'营业额'},
    {e:'revenue',c:'收入'},
    {e:'expenditure',c:'公司支出'},
    {e:'overdraft',c:'透支'},
    {e:'draft,remittance',c:'汇款'},
    {e:'maximum liability',c:'最高保额'},
    {e:'comprehensive insurance',c:'全险'},
    {e:'royalties',c:'版税'},
    {e:'statement of account',c:'会计报表'},
    {e:'stock exchange',c:'股票交易所'},
    {e:'tariff',c:'关税'},
    {e:'tax evasion',c:'逃税'},
    {e:'tender for ...',c:'为...竞标'},
    {e:'telegraphic transfer',c:'电汇'},
    {e:'trust fund',c:'信托基金'},
    {e:'withholding tax',c:'预扣税'},
    {e:'land title certificate',c:'土地所有权证书'},
    {e:'charge account',c:'赊账账户'},
    {e:'credit account',c:'信用账户'},
    {e:'term deposits',c:'定期存款'},
    {e:'brokerage',c:'佣金'},
    {e:'Building Societies',c:'建房互助协会'},
    {e:'butt/stub',c:'存根'},
    {e:'bearer',c:'持票人'},
    {e:'dishonoured cheque',c:'空头支票'},
    {e:'post-dated cheque',c:'期票'},
    {e:'clearing house',c:'票据交易所'},
    {e:'compound interest',c:'复利'},
    {e:'consumer credit',c:'消费者信贷'},
    {e:'consumer price index',c:'消费者价格指数'},
    {e:'Credit Union',c:'信用合作社'},
    {e:'Day of Grace',c:'宽限日'},
    {e:'debenture',c:'公司债券'},
    {e:'disposable income',c:'可支配收入'},
    {e:'dividend',c:'红利，分红'},
    {e:'earnings per share',c:'每股收入'},
    {e:'fiscal policy',c:'财政政策'},
    {e:'fixed/flexible rate loan',c:'固定/非固定利率贷款'},
    {e:'franchise',c:'特许经销权'},
    {e:'home equity',c:'房屋净值'},
    {e:'idle money',c:'闲钱'},
    {e:'inflation/deflation',c:'通货膨胀/紧缩'},
    {e:'demand-pull',c:'需求拉动的'},
    {e:'cost-push',c:'成本推动的'},
    {e:'lessor',c:'出租人'},
    {e:'lessee',c:'承租人'},
    {e:'limited liability',c:'有限责任'},
    {e:'liquidation',c:'清算'},
    {e:'maturity (in business)',c:'到期'},
    {e:'merchant bank',c:'商业银行'},
    {e:'mortgage',c:'抵押'},
    {e:'overdue',c:'逾期未付的'},
    {e:'passbook',c:'存折'},
    {e:'payment advice',c:'存款通知'},
    {e:'personal identification number',c:'个人身份号码'},
    {e:'portfolio investment',c:'投资组合'},
    {e:'prime rate',c:'最优利率'},
    {e:'property trust',c:'财产信托'},
    {e:'public listed company',c:'上市公司'},
    {e:'quotas',c:'配额'},
    {e:'third-party insurance',c:'第三方保险'},
    {e:'teller',c:'出纳'},
    {e:'upfront fees',c:'预付费用'},
    
]}