export default {name:'business',content:[
    {e:'income test',c:'收入检查'},
    {e:'asset test',c:'资产检查'},
    {e:'capital gains tax',c:'资本增值税'},
    {e:'premium',c:'保费'},
    {e:'goods and service tax',c:'消费税'},
    {e:'turnover',c:'营业额'},
    {e:'revenue',c:'收入'},
    {e:'expenditure',c:'公司支出'},
    {e:'overdraft',c:'透支'},
    {e:'draft,remittance',c:'汇款'},
    {e:'maximum liability',c:'最高保额'},
    {e:'comprehensive insurance',c:'全险'},
    {e:'rayalties',c:'版税'},
    {e:'statement of account',c:'会计报表'},
    {e:'stock exchange',c:'股票交易所'},
    {e:'tariff',c:'关税'},
    {e:'tax evasion',c:'逃税'},
    {e:'tender for ...',c:'为...竞标'},
    {e:'telegraphic transfer',c:'电汇'},
    {e:'trust fund',c:'信托基金'},
    {e:'withholding tax',c:'预扣税'},
    {e:'land title certificate',c:'土地所有权证书'},
]}