export default {name:'centrelink',content:[
    {e:'centrelink',c:'中央福利署'},
    {e:'first owner grant',c:'首次购房补助'},
    {e:'Department of Health',c:'健康部'},
    {e:'Department of Human Services',c:'民政服务部'},
    {e:'character check',c:'品格测试'},
    {e:'family balance test',c:'家庭平衡测试'},
    {e:'family composition',c:'家庭组成'},
    {e:'Administrative Appeals Tribunal',c:'行政上诉仲裁庭'},
    {e:'actively seeking work',c:'积极寻工'},
    {e:'nursing home',c:'疗养院'},
    {e:'OSHC',c:'海外留学生保险'},
    {e:'child care',c:'托儿'},
    {e:'annual leave',c:'年假'},
    {e:'age pension',c:'养老金'},
    {e:'arrears of compensation',c:'拖欠赔偿金'},
    {e:"I'm finished",c:'我下班了'},
    {e:'take one day off',c:'放一天假'},
    {e:'tax file number',c:'个人税号'},
    {e:'Australian business number',c:'澳大利亚商业号'},
    {e:'day care',c:'日托'},
    {e:'beneficiary',c:'受益人'},
    {e:'bulk billing',c:'公费医疗报销'},
    {e:'depreciation',c:'贬值'},
    {e:'be exempted from',c:'从...中豁免'},
    {e:'fares allowance',c:'交通津贴'},
    {e:'maternity leave',c:'产假'},
    {e:'notice of dismissal',c:'解雇通知'},
    {e:'payslip',c:'工资单'},
    {e:'reconciliation',c:'和解'},
    {e:'contractor',c:'承包商'},
    {e:'subcontractor',c:'分包商'},
    {e:'superannuation',c:'超级养老金'},
    {e:'title deed',c:'所有权合同'},
    {e:'understate income',c:'少报的收入'},
    {e:'undisclosed income',c:'未披露收入'},
    {e:'withhold',c:'扣除'},
]}