export default  {name:'immigration',content:[
    {e:'on a ... visa',c:'持有...签证'},
    {e:'family planning',c:'家庭计划'},
    {e:'Department of Immigration and Border Protection',c:'移民局'},
    {e:'Department of Home Affairs',c:'内政部'},
    {e:'approval',c:'批准'},
    {e:'consul',c:'领事'},
    {e:'embassy',c:'大使管'},
    {e:'embassador',c:'大使'},
    {e:'ethnic',c:'种族的'},
    {e:'grant',c:'授予'},
    {e:'nominee',c:'被担保人'},
    {e:'orientation',c:'迎新'},
    {e:'employability',c:'就业能力'},
    {e:'proscribed disease',c:'被禁止的疾病'},
    {e:'recognition of qualification',c:'职业认证'},
    {e:'induction',c:'入职'},
    {e:'Victorian Civil & Administrative Tribunal',c:'维多利亚民事行政仲裁庭'},
    {e:'tourist visa',c:'旅行者签证'},
]}