export default  {name:'law',content:[
    {e:'domestic violence',c:'家庭暴力'},
    {e:'apprehended violence order',c:'暴力逮捕令'},
    {e:'apprehended domestic violence order',c:'家庭暴力逮捕令'},
    {e:'custody',c:'1关押 2抚养权'},
    {e:'intervention order',c:'干预令'},
    {e:'constable',c:'巡警'},
    {e:'plain clothes officer',c:'便衣警官'},
    {e:'squad',c:'特警'},
    {e:'guard',c:'警卫'},
    {e:'prison warden',c:'典狱长'},
    {e:'be sentenced with...for...',c:'由于...，被判...'},
    {e:'be held in custody',c:'被关押'},
    {e:'win the custody of',c:'赢得...的抚养权'},
    {e:'civil/criminal',c:'民事/刑事'},
    {e:'commit an offense',c:'犯罪'},
    {e:'interrogate',c:'审讯'},
    {e:'search warrant',c:'搜查令'},
    {e:'abscond',c:'畏罪潜逃'},
    {e:'bail',c:'保释'},
    {e:'parole',c:'假释'},
    {e:'remand',c:'还押'},
    {e:'burglary',c:'入室行窃'},
    {e:'drive without due care',c:'疏忽驾驶'},
    {e:'embezzlement',c:'挪用公款'},
    {e:'comply with',c:'遵守'},
    {e:'forgery',c:'伪造罪'},
    {e:'robbery',c:'抢劫'},
    {e:'forge note',c:'伪造钞票'},
    {e:'straddling lanes',c:'跨线'},
    {e:'alibi',c:'不在场证明'},
    {e:'appeal',c:'上诉'},
    {e:'allege',c:'声称'},
    {e:'barrister',c:'大律师'},
    {e:'allegation',c:'声明'},
    {e:'statement',c:'陈述'},
    {e:'appeal in court',c:'上庭'},
    {e:'case,matter',c:'案件'},
    {e:'present a case',c:'上庭陈述案件'},
    {e:'charge ... with ...',c:'以...罪起诉...'},
    {e:'on a charge of ...',c:'被以...罪起诉'},
    {e:'damages',c:'赔偿金，损坏'},
    {e:'defendant',c:'被告'},
    {e:'forfeit',c:'没收，主动放弃'},
    {e:'magistrate',c:'地方法院'},
    {e:'plaintiff',c:'原告'},
    {e:'misconduct,misdemeanour',c:'不当行为'},
    {e:'libel',c:'诽谤'},
    {e:'nullify',c:'使无效'},
    {e:'slander,defamation,libel',c:'诽谤'},
    {e:'gossip',c:'说闲话'},
    {e:'deceased',c:'死亡状态的'},
]}