export default  {name:'medical',content:[
    {e:'Health Examination',c:'体检'},
    {e:'Blood Test',c:'血检'},
    {e:'anaesthetist',c:'麻醉师'},
    {e:'be allergic to',c:'对...过敏'},
    {e:'prostate cancer',c:'前列腺癌症'},
    {e:'deafness',c:'耳聋'},
    {e:'swelling',c:'肿胀'},
    {e:'get vaccinated against',c:'接种...疫苗'},
    {e:'cholera',c:'霍乱'},
    {e:'stroke',c:'中风'},
    {e:'heat stroke',c:'中暑'},
    {e:'menarche',c:'月经初潮'},
    {e:'menopause',c:'更年期'},
    {e:'steroid',c:'类固醇'},
    {e:'cholesteral',c:'胆固醇'},
    {e:'mumps',c:'腮腺炎'},
    {e:'defecate',c:'排便'},
    {e:'urinate',c:'排尿'},
    {e:'triple antigen',c:'三联抗原'},
    {e:'diptheria',c:'白喉'},
    {e:'turberculosis',c:'肺结核'},
    {e:'hepatitus B',c:'乙肝'},
    {e:'tetanus',c:'破伤风'},
    {e:'whooping cough',c:'百日咳'},
    {e:'benign/malignant tumour',c:'良性/恶性肿瘤'},
    {e:'antibiotic',c:'抗生素'},
    {e:'crutches',c:'三角拐杖'},
    {e:'chemotherapy',c:'化疗'},
    {e:'dementia',c:'老年痴呆症'},
    {e:'measles',c:'麻疹'},
    {e:'haemorrhage',c:'大出血'},
    {e:'haemorrhoids',c:'痔疮'},
    {e:'hay fever',c:'花粉热'},
    {e:'pneumonia',c:'肺炎'},
    {e:'rheumatic heart disease',c:'风湿性心脏病'},
]}