export default  {name:'medical',content:[
    {e:'Health Examination',c:'体检'},
    {e:'Blood Test',c:'血检'},
    {e:'anaesthetist',c:'麻醉师'},
    {e:'be allergic to',c:'对...过敏'},
    {e:'prostate cancer',c:'前列腺癌症'},
    {e:'deafness',c:'耳聋'},
    {e:'swelling',c:'肿胀'},
    {e:'get vaccinated against',c:'接种...疫苗'},
    {e:'cholera',c:'霍乱'},
    {e:'stroke',c:'中风'},
    {e:'heat stroke',c:'中暑'},
    {e:'menarche',c:'月经初潮'},
    {e:'menopause',c:'更年期'},
    {e:'steroid',c:'类固醇'},
    {e:'cholesteral',c:'胆固醇'},
    {e:'mumps',c:'腮腺炎'},
    {e:'defecate',c:'排便'},
    {e:'urinate',c:'排尿'},
    {e:'triple antigen',c:'三联抗原'},
    {e:'diptheria',c:'白喉'},
    {e:'turberculosis',c:'肺结核'},
    {e:'hepatitus B',c:'乙肝'},
    {e:'tetanus',c:'破伤风'},
    {e:'whooping cough',c:'百日咳'},
    {e:'benign/malignant tumour',c:'良性/恶性肿瘤'},
    {e:'antibiotic',c:'抗生素'},
    {e:'crutches',c:'三角拐杖'},
    {e:'chemotherapy',c:'化疗'},
    {e:'dementia',c:'老年痴呆症'},
    {e:'measles',c:'麻疹'},
    {e:'haemorrhage',c:'大出血'},
    {e:'haemorrhoids',c:'痔疮'},
    {e:'hay fever',c:'花粉热'},
    {e:'pneumonia',c:'肺炎'},
    {e:'rheumatic heart disease',c:'风湿性心脏病'},
    {e:'physiotherapist',c:'理疗师'},
    {e:'cardiology',c:'心脏科'},
    {e:'denture',c:'假牙'},
    {e:'gynaecologist',c:'妇科医生'},
    {e:'maternity',c:'母婴'},
    {e:'obstetrician',c:'产科医生'},
    {e:'oncologist',c:'肿瘤科医生'},
    {e:'ophthalmologist',c:'眼科医生'},
    {e:'paediatrician',c:'儿科医生'},
    {e:'pathologist',c:'病理学家'},
    {e:'garlic intolerance',c:'大蒜不耐受'},
    {e:'local anaesthetic',c:'局部麻醉'},
    {e:'general anaesthetic',c:'全麻'},
    {e:'renal dialysis',c:'肾透析'},
    {e:'urinary tract infection',c:'尿道感染'},
    {e:'kidney stone',c:'肾结石'},
    {e:'lower back pain',c:'腰疼'},
    {e:'infectious/contagious',c:'有传染性的'},
    {e:'gall inflammation',c:'胆囊炎'},
    {e:'collapse',c:'昏倒，崩溃'},
    {e:'ringing of the year',c:'耳鸣'},
    {e:'amnesia',c:'健忘症'},
    {e:'anaemia',c:'贫血'},
    {e:'anorexia',c:'厌食症'},
    {e:'artery',c:'动脉'},
    {e:'vein',c:'静脉'},
    {e:'arthritis',c:'关节炎'},
    {e:'asthma',c:'哮喘'},
    {e:'cataract',c:'白内障'},
    {e:'complications',c:'并发症'},
    {e:'cloudy lens',c:'晶状体浑浊'},
    {e:'abortion',c:'流产'},
    {e:'be aged',c:'上年纪'},
    {e:'grazed',c:'擦伤'},
    {e:'laxative',c:'泻药'},
    {e:'be diagnosed with',c:'被诊断为...'},
    {e:'diagnosis',c:'诊断'},
    {e:'insomnia',c:'失眠'},
    {e:'post-mortem',c:'尸检'},
    {e:'nausea',c:'恶心'},
    {e:'fluid',c:'积液'},
    {e:'coma',c:'昏迷'},
    {e:'emphysema',c:'肺气肿'},
    {e:'eczema',c:'湿疹'},
    {e:'some kind of symptom',c:'未听懂是什么症状时候的补救'},
    {e:'glaucoma',c:'青光眼'},
    {e:'hernia',c:'疝气'},
    {e:'hypertension,high blood pressure',c:'高血压'},
    {e:'hypotension,low blood pressure',c:'低血压'},
    {e:'urinary/faecal incontinence',c:'小/大便失禁'},
    {e:'influenza/flu',c:'流感'},
    {e:'hip',c:'臀部'},
    {e:'ankle',c:'脚踝'},
    {e:'leukaemia',c:'白血病'},
    {e:'meningitus',c:'脑膜炎'},
    {e:'migrane',c:'偏头痛'},
    {e:'miscarriage',c:'流产'},
    {e:'pleurity',c:'胸膜炎'},
    {e:'polio',c:'小儿麻痹'},
    {e:'sciatica',c:'坐骨神经痛'},
    {e:'scalp',c:'头皮'},
    {e:'shingles',c:'带状疱疹'},
    {e:'analgesic, pain killer',c:'止痛剂'},
    {e:'insulin',c:'胰岛素'},
    {e:'dropper',c:'点滴'},
    {e:'eye drops',c:'眼药水'},
    {e:'disinfectant',c:'消毒剂'},
    {e:'dosage',c:'剂量'},
    {e:'get injected with',c:'注射...'},
    {e:'lozenges',c:'含片'},
    {e:'ointment',c:'膏体'},
    {e:'orally',c:'口腔地'},
    {e:'plaster',c:'石膏'},
    {e:'sedative',c:'镇定剂'},
    {e:'stretcher',c:'担架'},
    {e:'thermometer',c:'温度计'},
    {e:'urinal',c:'小便池'},
]}